---
title: "About Me"
---

I was raised in a small beachtown called Carpinteria in California. It is about
a 15 minute drive from Santa Barbara and about 1.5 hour drive north of LAX. I am
a first generation college student. My parents immigrated from Mexico and I am
forever grateful for their sacrifices so that I could have more opportunities. A fun
fact is my name translates to "Ocean and Sun" and my parents chose this name for me
because since I was born in Santa Barbara near the ocean and (mostly always) sunny skies
they felt like it was fitting. Out of highschool, I went to school at Cal Poly SLO, however, I quickly realized it was not for me and I came back to Santa Barbara. Now I go to CSU Channel Islands and in the short time I have been at CI I have felt very supported and been given many opportunites. On my free time, I enjoy going to the beach, hiking,concerts with friends,traveling, and spending time with family. During the winter when it is colder I like to watch movies, listen to music, and read.
